// Generated by CoffeeScript 2.3.1
var self;

self = function() {
  var deps, sass;
  this.merge('exts', ['.sass']);
  deps = this.root.data.devDependencies;
  if (deps != null ? deps['node-sass'] : void 0) {
    sass = require(this.resolve('node_modules/node-sass'));
    return this.hook('bundle', function(css, bundle) {
      var map;
      ({css, map} = sass.renderSync({
        data: css,
        file: '',
        outFile: 'bundle.css',
        sourceMap: true,
        omitSourceMapUrl: true,
        indentedSyntax: true,
        outputStyle: bundle.outputStyle || 'compressed'
      }));
      return {
        content: css.toString(),
        map: JSON.parse(map.toString())
      };
    });
  }
};

self.worker = require.resolve('./worker');

module.exports = self;
