// Generated by CoffeeScript 2.3.1
var enabled, lexer, tokenizer;

lexer = require('sass-lexer');

enabled = Symbol('sass:enabled');

tokenizer = function(opts) {
  var toks;
  toks = lexer(opts.css);
  return {
    atrule: 'atrule',
    evalStrings: false,
    getLength: function(prev) {
      return prev[2];
    },
    importWord: 'import',
    nextToken: function() {
      return toks.next();
    },
    semi: false
  };
};

module.exports = function() {
  return this.transform('.sass', function(asset, pack) {
    asset.ext = '.css';
    if (!pack[enabled]) {
      pack[enabled] = true;
      pack.tokenize = tokenizer;
    }
  });
};
